//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.Res.Advaned
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceList
    {
        public int ID_ServiceList { get; set; }
        public int Order_ID { get; set; }
        public int Service_ID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
